#!/bin/sh

docker run -it --rm \
    -v /tmp/.X11-unix:/tmp/.X11-unix  \
    -v `pwd`:/work \
    -e DISPLAY=unix$DISPLAY \
    -v $HOME/.gitconfig:/devhome/.gitconfig \
    --device /dev/dri \
    -e HOSTUSER=`id -un` \
    -e HOSTGROUP=`id -gn` \
    -e HOSTUSERID=`id -u` \
    -e HOSTGROUPID=`id -g` \
    vsc


