#!/bin/sh

# privileged is needed by delve debugger ...
# also pass in the current working-directory so the source path's
# in the go-binaries will be correct if the binary is built outside

docker run -it --rm \
    --privileged \
    -v /tmp/.X11-unix:/tmp/.X11-unix  \
    -v `pwd`:`pwd` \
    -v $HOME/.config:/config \
    -e DISPLAY=unix$DISPLAY \
    -v $HOME/.gitconfig:/devhome/.gitconfig \
    -v $SSH_AUTH_SOCK:/ssh-agent --env SSH_AUTH_SOCK=/ssh-agent \
    -v $HOME/.git-credential-cache:/devhome/.git-credential-cache \
    -v /var/run/dbus:/var/run/dbus:ro \
    -v /etc/machine-id:/etc/machine-id:ro \
    -v /run/docker.sock:/run/docker.sock:ro \
    -e XAUTHORITY=/.XAUTHORITY -v $XAUTHORITY:/.XAUTHORITY \
    --device /dev/dri \
    --device /dev/snd \
    -e LANG=$LANG \
    -e HOSTUSER=`id -un` \
    -e HOSTGROUP=`id -gn` \
    -e HOSTUSERID=`id -u` \
    -e HOSTGROUPID=`id -g` \
    -e WORKSPACE=`pwd` \
    -e DISABLE_GPU="--disable-gpu" \
    quay.io/ulrichschreiner/vsc "$@"
